### ISSUE TITLE
Add Outline View

### ISSUE THREAD

**Issue by perego86** [ahnooie/vscode-gembase-dml#8]
I have installed the Gembase extension on vscode and it is working. But I would like to know if it is possible 
to show the Function List like "notepad++" did. 

This function it is very nice to find the procedure easily.

![image](https://user-images.githubusercontent.com/3808368/53922554-a0750e80-4053-11e9-876b-14ee8ab0fbc1.png)

Thank you a lot.

**Comment by nmacro** [comment]
I checked with Ben a few weeks ago with the same request.
The function list in Notepad++ is "outline view" in VSCode
The current version of this extension doesn't support outline view.

Ben is too busy to make it, he gave me the direction on how to make it.
And I am working on it, made some progress.
![dml-outline](https://user-images.githubusercontent.com/1113345/53945945-b2ab8700-40fd-11e9-860a-e87acc57f8e6.JPG)

I am still making changes and testing.
Will report back when it is done. 

@ahnooie , Hi Ben, please assign this issue to me.

**Comment by perego86** [comment]
It seems that is getting great. Let me know if I can help you out. 
Adding this feature to VS I will retire my notepad++. :)

**Comment by ahnooie** [comment]
That looks nice @nmacro   I can't assign the issue to you (GitHub will only allow me to assign it to perego86 or myself which seems odd).  I assume you can't assign it to yourself either?

**Comment by jordiagp** [comment]
Hi, do you have any progress on this? This function list is very important while programming in Gembase.
I appreciate so much your time doing this.
Regards,
Jordi A.

**Comment by DubMatrix** [comment]
I'm currently working on this issue and was wondering which things to parse, what would be interesting? Right now I've created an outline parser to display FORMS and BLOCKS, using the images for Class and Function. Any extra information is welcome. On the left what I have now and on the right possible images / symbols to use:

![image](https://user-images.githubusercontent.com/39420029/146243256-8a331752-1586-4c46-8859-1493534fbb15.png)________![image](https://user-images.githubusercontent.com/39420029/146254346-6f9434e5-4d2f-4155-9d8a-52421e816678.png)

**Comment by ahnooie** [comment]
Good work @DubMatrix 

I just tested it and it works great.  I showed your outline to a few DML Developers,  and they think what you have (Forms and Blocks) is perfect.  Are you ready for me to merge it in or do you want to make any more changes?

**Comment by DubMatrix** [comment]
Hello,

Thanks, I think it is ok to merge as it is right now. We can always improve
or correct when needed.

Kind regards, Romano

**Comment by ahnooie** [comment]
Just published your changes to the marketplace.  Thank you.
